[technote]
id = "TSTN-065"
series_id = "TSTN"
canonical_url = "https://tstn-065.lsst.io"
github_url = "https://github.com/lsst-tstn/tstn-065"
github_default_branch = "main"
date_created = 2026-07-20T17:57:24Z
organization.name = "NSF-DOE Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Parker"
name.family = "Fagrelius"
internal_id = "fagreliusp"

[[technote.authors.affiliations]]
name = "NSF-DOE Vera C. Rubin Observatory / NSF NOIRLab"
internal_id = "RubinObs"
address = "Tucson"
